spring:
  h2:
    # login via localhost:8080/h2-console
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
